# Generated by Django 6.0.5 on 2026-05-26 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityprofile',
            name='appointment_letter',
            field=models.FileField(blank=True, help_text='Official Gazette notice or appointment letter copy', null=True, upload_to='authority_docs/'),
        ),
        migrations.AddField(
            model_name='authorityprofile',
            name='assigned_ward',
            field=models.ForeignKey(blank=True, help_text='The localized area/ward this official governs and receives targeted complaint notifications for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_authorities', to='locations.unionward'),
        ),
        migrations.AddField(
            model_name='authorityprofile',
            name='official_id_card',
            field=models.ImageField(blank=True, help_text='Upload Government Badge, ID, or Employee Card', null=True, upload_to='authority_proofs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_number',
            field=models.CharField(blank=True, help_text='10 or 17-digit National Identity Card Number', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authorityprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid_document',
            field=models.FileField(blank=True, help_text='PDF scan or clear photo image of the physical NID card', null=True, upload_to='nid_docs/'),
        ),
    ]
